/tmp/tmpwdco0dom:135:21-22: error: syntax error, unexpected (

/tmp/tmpwdco0dom:136:73-74: error: syntax error, unexpected (

/tmp/tmpwdco0dom:137:48-49: error: syntax error, unexpected (

/tmp/tmpwdco0dom:139:80-81: error: syntax error, unexpected (

/tmp/tmpwdco0dom:140:60-61: error: syntax error, unexpected (

/tmp/tmpwdco0dom:142:95-96: error: syntax error, unexpected (

/tmp/tmpwdco0dom:143:65-66: error: syntax error, unexpected (

/tmp/tmpwdco0dom:145:88-89: error: syntax error, unexpected (

/tmp/tmpwdco0dom:146:67-68: error: syntax error, unexpected (

/tmp/tmpwdco0dom:148:97-98: error: syntax error, unexpected (

/tmp/tmpwdco0dom:149:62-63: error: syntax error, unexpected (

/tmp/tmpwdco0dom:150:63-64: error: syntax error, unexpected (

/tmp/tmpwdco0dom:152:101-102: error: syntax error, unexpected (

/tmp/tmpwdco0dom:153:66-67: error: syntax error, unexpected (

/tmp/tmpwdco0dom:154:67-68: error: syntax error, unexpected (

/tmp/tmpwdco0dom:156:81-82: error: syntax error, unexpected (

/tmp/tmpwdco0dom:157:50-51: error: syntax error, unexpected (

/tmp/tmpwdco0dom:158:58-59: error: syntax error, unexpected (

/tmp/tmpwdco0dom:160:85-86: error: syntax error, unexpected (

/tmp/tmpwdco0dom:161:50-51: error: syntax error, unexpected (

*** ERROR: (gringo): too many messages.
Traceback (most recent call last):
  File "test.py", line 174, in <module>
    actions = grounding.ground_actions()
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 39, in ground_actions
    model = self._solve_lp()
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 50, in _solve_lp
    model_filename = run_clingo(lp)
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/reachability/clingo_wrapper.py", line 26, in run_clingo
    raise ExternalCommandError("Gringo exited with code {}".format(retcode))
tarski.errors.ExternalCommandError: Gringo exited with code 1
