***Started - reading and parsing pddl file ...***
***Finished reading and parsing pddl file after 0.629 seconds CPU time, 0.620 seconds wall-clock time***

***Started - preprocessing tarski problem ...***
***Finished preprocessing tarski problem after 0.001 seconds CPU time, 0.001 seconds wall-clock time***

***Started - grounding ...***
/tmp/tmp82n9h7ol:9:26-27: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:10:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:11:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:13:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:14:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:16:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:17:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:19:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:20:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:22:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:23:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:25:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:26:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:28:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:29:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:31:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:32:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:34:56-57: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:35:59-60: error: syntax error, unexpected (

/tmp/tmp82n9h7ol:37:43-44: error: syntax error, unexpected (

*** ERROR: (gringo): too many messages.
Traceback (most recent call last):
  File "brfs.py", line 60, in <module>
    main( sys.argv[1], sys.argv[2], sys.argv[3] )
  File "brfs.py", line 15, in main
    ground_generate_task( domain_file, problem_file, task )
  File "/home/anubhav-cs/Documents/Research_Project/anubhav-research/LAPKT-public/planners/brfs-tarski/tarski_parser/tarski_util.py", line 185, in ground_generate_task
    reachable_action_params =   copy.deepcopy( grounding.ground_actions())
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 39, in ground_actions
    model = self._solve_lp()
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/grounding/lp_grounding.py", line 50, in _solve_lp
    model_filename = run_clingo(lp)
  File "/media/anubhav-cs/SSD256/Applications/tarski/src/tarski/reachability/clingo_wrapper.py", line 26, in run_clingo
    raise ExternalCommandError("Gringo exited with code {}".format(retcode))
tarski.errors.ExternalCommandError: Gringo exited with code 1
