ERROR:root:message
Traceback (most recent call last):
  File "tarski_test.py", line 30, in main
    status = ground_generate_task( domain_file, problem_file, None, verbose, lenient)
  File "/home/anubhav-cs/Github/tarski/tests/classical_planning-test_suite/tarski_util.py", line 101, in ground_generate_task
    read_problem( domain_file, problem_file)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/fstrips.py", line 43, in read_problem
    self.parse_domain(domain)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/fstrips.py", line 53, in parse_domain
    self.parse_file(filename, 'domain')
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/fstrips.py", line 50, in parse_file
    self.parser.visit(domain_parse_tree)
  File "/usr/local/lib/python3.7/dist-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/parser/parser.py", line 803, in accept
    return visitor.visitDomain(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/parser/visitor.py", line 19, in visitDomain
    return self.visitChildren(ctx)
  File "/usr/local/lib/python3.7/dist-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/parser/parser.py", line 1020, in accept
    return visitor.visitDeclaration_of_types(self)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/reader.py", line 87, in visitDeclaration_of_types
    create_sort(self.language, typename, basename)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/io/_fstrips/common.py", line 94, in create_sort
    lang.sort(typename, lang.get_sort(basename))
  File "/home/anubhav-cs/Applications/tarski/src/tarski/fol.py", line 104, in sort
    return self.attach_sort(Sort(name, self), parent)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/fol.py", line 108, in attach_sort
    self._check_name_not_defined(sort.name, self._sorts, err.DuplicateSortDefinition)
  File "/home/anubhav-cs/Applications/tarski/src/tarski/fol.py", line 242, in _check_name_not_defined
    raise exception(name, where[name])
tarski.errors.DuplicateSortDefinition: Duplicate definition of element "area": "Sort(area)"
